### ISSUE TITLE
Unable to export in csv format

### ISSUE THREAD

**Issue by DocKali** [leapsecurity/InSpy#15]
It's me again. This time I try to export InSpy result in csv format.
InSpy find all the informations, no problem. But when I ask to export (via flag --csv file), I have the following problem : 

```
Traceback (most recent call last):
  File "InSpy.py", line 82, in <module>
    output("csv", args.csv, args.company, domain, employees, emails)
  File "/usr/toolz/InSpy/lib/export.py", line 8, in output
    ocsv(file, company, domain, employees, emails)
  File "/usr/toolz/InSpy/lib/export.py", line 18, in ocsv
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
NameError: global name 'csv' is not defined
```

I don't understand where the error come from. Is it the tool or me?

**Comment by gojhonny** [comment]
Bug/Error from tool. I'll work on it and release an update. Thanks!

**Comment by DocKali** [comment]
Glad to help you finding a bug. Good luck for the new release...

**Comment by DocKali** [comment]
Hi,
With the latest release you publish, there's no more error message when asking your tool to export in csv. But I can't see any message confirming the export was done and I can't find the file where it's stored. Do you have more infos about that?

**Comment by gojhonny** [comment]
It should be within your working directory.

**Comment by DocKali** [comment]
Hi Jhonny,
I try to export in csv and in json, I have no error messages but I still can't find where the files are. I search in InSpy's folder, I can't find anything.
Thanks for your help!

**Comment by gojhonny** [comment]
Can you show me the command you are using? Thanks!

**Comment by DocKali** [comment]
Hi @gojhonny 
Sorry for the late answer. The command I use is the following : 
`python2.7 InSpy.py Company --csv file`
The tool works well and find all employees and their title but when I go in InSpy's folder, there's no export file...
