### ISSUE TITLE
IOError

### ISSUE THREAD

**Issue by Prin777** [leapsecurity/InSpy#22]
Traceback (most recent call last):
  File "Inspy.py", line 28, in <module>
    start_logger(args.company)
  File "C:\InSpy-master\lib\logger.py", line 6, in start_logger
    handler = logging.FileHandler('./logs/{}_{}.log'.format(company.replace(' ', '_'), time_format.replace(' ', '_')))
  File "C:\Python27\lib\logging\__init__.py", line 920, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Python27\lib\logging\__init__.py", line 950, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 22] invalid mode ('a') or filename: 'C:\\InSpy-master\\logs\\acme_2018-12-03_00:11:38.log'

**Comment by tianyilt** [comment]
the same as me in win10 python=2.7 after running `InSpy acme --domain acme.com --email first.last --xml file`
