### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by gbiagomba** [leapsecurity/InSpy#23]
Hello,

I been having issues with running inspy, I keep getting the below error regardless of what I do. 

```
root@GBiagomba-Kali:/opt/TEST/InSpy# ./InSpy.py --domain example.com --email lfirst@example.com --csv example.csv example

InSpy 3.0.1

Domain: example.com, Email Format: lfirst@example.com

Traceback (most recent call last):
  File "./InSpy.py", line 56, in <module>
    for response in search_linkedin(args.company, os.path.abspath(args.titles)):
  File "/opt/TEST/InSpy/lib/workbench.py", line 65, in search_linkedin
    if response["status"] == 200:
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by gbiagomba** [comment]
I found out what the issue was, our firewall was blocking the script from making calls sigh
