### ISSUE TITLE
ImportError: No module named BeautifulSoup

### ISSUE THREAD

**Issue by makmour** [leapsecurity/InSpy#28]
Fresh install under ParrotSec OS

sudo python2.7 InSpy.py -h
Traceback (most recent call last):
  File "InSpy.py", line 7, in <module>
    from lib.soup import *
  File "/usr/var/InSpy/lib/soup.py", line 1, in <module>
    import BeautifulSoup, json
ImportError: No module named BeautifulSoup

**Comment by mgogic1** [comment]
ICan you check what type of Beautiful Soup you have installed? It is possible that by accident BeautifulSoup 4 is installed.

**Comment by TheCyberMonster** [comment]
change 
import beautifulsoup 
to
from bs4 import beautifulsoup 
and install beautifulsoup4 python library
