### ISSUE TITLE
HAVING THE BELOW ERROR CODE, PLEASE HELP TO FIX IT

### ISSUE THREAD

**Issue by Crewxx** [leapsecurity/InSpy#29]
Traceback (most recent call last):
  File "InSpy.py", line 56, in <module>
    for response in search_linkedin(args.company, os.path.abspath(args.titles)):
  File "/home/beckox/InSpy/lib/workbench.py", line 65, in search_linkedin
    if response["status"] == 200:
TypeError: 'NoneType' object has no attribute '__getitem__'

WHAT SHOULD I DO, HOW CAN I RESOLVE THIS?
THANKS IN ADVANCE FOR YOUR SUPPORT.

**Comment by Crewxx** [comment]
@gojhonny

**Comment by yanlimeng** [comment]
idem..

Traceback (most recent call last):
File "./InSpy.py", line 5, in <module>
from lib.http import*

File "/home/I/InSpy/lib/http.py", line 2, in <module>
import request, random
ImportError: No module named requests
