### ISSUE TITLE
Error Inspy 

### ISSUE THREAD

**Issue by bitmichel** [leapsecurity/InSpy#34]
Hi Pals:

when i execute "python InSpy.py bdp --domain bdp.com.bo --email first.last@bdp.com.bo --xml"

I have the next message, please:

InSpy 3.0.1

Domain: bdp.com.bo, Email Format: first.last@bdp.com.bo

0 Employees identified
Traceback (most recent call last):
  File "InSpy.py", line 85, in <module>
    output("xml", args.xml, args.company, domain, employees, emails)
NameError: name 'emails' is not defined

Please HELP

Bit

**Comment by bitmichel** [comment]
I have other message:

python InSpy.py --domain go.com go

InSpy 3.0.1

Domain: go.com, Email Format: firstlast

Traceback (most recent call last):
  File "InSpy.py", line 56, in <module>
    for response in search_linkedin(args.company, os.path.abspath(args.titles)):
  File "/home/masti10/InSpy/lib/workbench.py", line 65, in search_linkedin
    if response["status"] == 200:
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by dirtytribal** [comment]
Hello,

I have the same problem

**Comment by danfelt** [comment]
# +--------------------+
# | Same problem here: |
# +--------------------+
root@kali:~/InSpy# python InSpy.py google --domain google.com

InSpy 3.0.1

Domain: google.com, Email Format: firstlast

0 Employees identified

# +---------------------------------+
# | Here is the log file for this search: |
# +---------------------------------+
2020-04-08 14:45:27,413 INFO - HunterIO Returned Email Format: {first}{last}
2020-04-08 14:45:28,028 ERROR - LinkedIn Search - HTTP 404 Error Crawling sales
2020-04-08 14:45:28,243 ERROR - LinkedIn Search - HTTP 404 Error Crawling marketing
2020-04-08 14:45:28,490 ERROR - LinkedIn Search - HTTP 404 Error Crawling human resources
2020-04-08 14:45:28,686 ERROR - LinkedIn Search - HTTP 404 Error Crawling finance
2020-04-08 14:45:30,837 ERROR - LinkedIn Search - HTTP 404 Error Crawling accounting
2020-04-08 14:45:30,085 ERROR - LinkedIn Search - HTTP 404 Error Crawling inventory
...
