### ISSUE TITLE
Error in install reuirements.txt  because of BeautifulSoup3.2.1 - Kali linux 

### ISSUE THREAD

**Issue by kigyousensi** [leapsecurity/InSpy#40]
I tried to install InSpy into Kali linux following command.

$ git clone https://github.com/leapsecurity/InSpy.git
$ cd InSpy
$ pip install -r requirements.txt

however, I got following error.

> Collecting BeautifulSoup==3.2.1
  Using cached BeautifulSoup-3.2.1.tar.gz (31 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mpgemcbm/BeautifulSoup/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mpgemcbm/BeautifulSoup/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-gsz35pi1                                                
         cwd: /tmp/pip-install-mpgemcbm/BeautifulSoup/                                        
    Complete output (6 lines):                                                                
    Traceback (most recent call last):                                                        
      File "<string>", line 1, in <module>                                                    
      File "/tmp/pip-install-mpgemcbm/BeautifulSoup/setup.py", line 22                        
        print "Unit tests have failed!"                                                       
              ^                                                                               
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Unit tests have failed!")?                                                                                     
    ----------------------------------------                                                  
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.     

Meybe python3 can't use BeautifulSoup 3.x.

**Solution (tempolary)**

Rewrite lib/soup.py instead of "pip install -r requirement.txt".
1) install beautifulsoup4
$ pip install beautifulsoup4

2) rewrite lib/soup.py 
before lib/soup.py line 1
> import BeautifulSoup,json

after lib/soup.py line 1
> import bs4 ,json

3) run inspy.py
$ ./InSpy --domain abc.com --email username abc

**Comment by yanlimeng** [comment]
$ ./InSpy      --domain abc.com --email username abc
$ ./InSpy**.py** --domain abc.com --email username abc

Still not working...:(
