### ISSUE TITLE
Requirements.txt install is returning an error

### ISSUE THREAD

**Issue by MandoMOTM** [leapsecurity/InSpy#44]
This is the output after inputting "pip3 install -r requirements.txt" 

`
Collecting requests==2.20.1
  Using cached requests-2.20.1-py2.py3-none-any.whl (57 kB)
Collecting BeautifulSoup==3.2.1
  Using cached BeautifulSoup-3.2.1.tar.gz (31 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-uj796awn/beautifulsoup_d7350856f0bb4996aeb10ca47c946245/setup.py'"'"'; __file__='"'"'/tmp/pip-install-uj796awn/beautifulsoup_d7350856f0bb4996aeb10ca47c946245/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-bgy8gurw
         cwd: /tmp/pip-install-uj796awn/beautifulsoup_d7350856f0bb4996aeb10ca47c946245/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-uj796awn/beautifulsoup_d7350856f0bb4996aeb10ca47c946245/setup.py", line 22
        print "Unit tests have failed!"
              ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Unit tests have failed!")?
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/1e/ee/295988deca1a5a7accd783d0dfe14524867e31abb05b6c0eeceee49c759d/BeautifulSoup-3.2.1.tar.gz#sha256=6a8cb4401111e011b579c8c52a51cdab970041cc543814bbd9577a4529fe1cdb (from https://pypi.org/simple/beautifulsoup/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement BeautifulSoup==3.2.1
ERROR: No matching distribution found for BeautifulSoup==3.2.1
`

**Comment by Alaponuke** [comment]
I have another error too:
Collecting requests==2.20.1
  Downloading requests-2.20.1-py2.py3-none-any.whl (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.0/58.0 kB 320.6 kB/s eta 0:00:00
Collecting BeautifulSoup==3.2.1
  Downloading BeautifulSoup-3.2.1.tar.gz (31 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-d4hji6ue/beautifulsoup_8c4155d27751416982fe6a09ed08a4f9/setup.py", line 22
          print "Unit tests have failed!"
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

![inspy error](https://user-images.githubusercontent.com/92026112/178738636-093a3a83-8bae-44f1-8a01-9122669158be.png)
